apiVersion: v1
kind: ConfigMap
metadata:
  name: telcobss-config
  namespace: telcobss
data:
  COUCHBASE_URL: "couchbase://couchbase"
  COUCHBASE_USER: "Administrator"
  COUCHBASE_PASSWORD: "password"
  MYSQL_DSN: "root:password@tcp(mysql:3306)/telco_bss"
  KAFKA_BROKERS: "kafka:9092"
  USAGE_TOPIC: "usage_events"
  RATED_TOPIC: "rated_events"
