apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: telcobss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: telcobss/billing-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: MYSQL_DSN
              valueFrom:
                configMapKeyRef:
                  name: telcobss-config
                  key: MYSQL_DSN
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: telcobss-config
                  key: KAFKA_BROKERS
