apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-engine
  namespace: telcobss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-engine
  template:
    metadata:
      labels:
        app: rating-engine
    spec:
      containers:
        - name: rating-engine
          image: telcobss/rating-engine:latest
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: telcobss-config
                  key: KAFKA_BROKERS
            - name: USAGE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: telcobss-config
                  key: USAGE_TOPIC
            - name: RATED_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: telcobss-config
                  key: RATED_TOPIC
